routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\Basic\LangController;
use App\Http\Controllers\Admin\Basic\ContactController;
use App\Http\Controllers\Admin\Basic\AboutController;
use App\Http\Controllers\Admin\Request\RequestController;
use App\Http\Controllers\Admin\Dashboard\DashboardController;
use App\Http\Controllers\Admin\User\SettingController;

use App\Http\Controllers\Site\Home\HomeController;
use App\Http\Controllers\Site\About\AboutController as SiteAboutController;
use App\Http\Controllers\Admin\Contact\ContactController as SiteContactController;
use App\Http\Controllers\Site\Team\TeamController as SiteTeamController;
use App\Http\Controllers\Site\Service\ServiceController as SiteServiceController;
use App\Http\Controllers\Site\Blog\BlogController as SiteBlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Site routes
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'siteVisits']
    ], function () {

    Route::name('site.')->group(function() {
        Route::get('/', [HomeController::class, 'index'])->name('index');
        Route::get('/about', [SiteAboutController::class, 'index'])->name('about');
        Route::get('/contacts', [SiteContactController::class, 'index'])->name('contact');
        Route::get('/team', [SiteTeamController::class, 'index'])->name('team');
        Route::get('/services', [SiteServiceController::class, 'index'])->name('service');
        Route::get('/service/details', [SiteServiceController::class, 'details'])->name('service-details');
        Route::get('/blog', [SiteBlogController::class, 'index'])->name('blog');
        Route::get('/blog/details', [SiteBlogController::class, 'details'])->name('blog-details');
        Route::get('/product/{id}', [SiteProductController::class, 'show'])->name('product');
        Route::get('/search', [HomeController::class, 'searchData'])->name('search');
    });
});

// Admin routes
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/admin', function () {
    return redirect('admin/home');
});
Route::prefix('/admin')->name('admin.')->middleware('role:admin')->group(function() {

    Route::get('/home', [DashboardController::class, 'index'])->name('index');

    Route::get('setting/edit',[SettingController::class, 'edit'])->name('setting.edit');
    Route::post('setting/update',[SettingController::class, 'update'])->name('setting.update');

    // Languages
    Route::prefix('languages')->name('language.')->group(function(){
        Route::get('/index', [LangController::class, 'index'])->name('index');
        Route::get('/show/{lang}', [LangController::class, 'show'])->name('show');
        Route::get('/edit/{lang}', [LangController::class, 'edit'])->name('edit');
        Route::get('/create', [LangController::class, 'create'])->name('create');
        Route::post('/store', [LangController::class, 'store'])->name('store');
        Route::post('/update/{lang}', [LangController::class, 'update'])->name('update');
    });

    // Contacts
    Route::prefix('contacts')->name('contact.')->group(function(){
        Route::get('/index', [ContactController::class, 'index'])->name('index');
        Route::get('/edit/{contact}', [SiteContactController::class, 'edit'])->name('edit');
        Route::post('/store', [SiteContactController::class, 'store'])->name('store');
        Route::post('/update/{contact}', [SiteContactController::class, 'update'])->name('update');
    });

    // About
    Route::prefix('about')->name('about.')->group(function(){
        Route::get('/index', [AboutController::class, 'index'])->name('index');
        Route::get('/edit', [AboutController::class, 'edit'])->name('edit');
        Route::post('/update', [AboutController::class, 'update'])->name('update');
    });

    // Requests
    Route::prefix('requests')->name('request.')->group(function(){
        Route::get('/index', [RequestController::class, 'index'])->name('index');
        Route::get('/show/{request}', [RequestController::class, 'show'])->name('show');
    });
});

app/Models/Request/Request.php
<?php

namespace App\Models\Request;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Request extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Http/Controllers/Admin/Request/RequestController.php
<?php

namespace App\Http\Controllers\Admin\Request;

use App\Http\Controllers\Controller;
use App\Models\Request\Request;

class RequestController extends Controller
{
    public function index()
    {
        $requests = Request::orderByDesc('created_at')->get();
        return view('pages.request.index', compact('requests'));
    }

    public function show(Request $request)
    {
        $request->update(['status' => 1]);
        return view('pages.request.show', compact('request'));
    }
}

resources/views/pages/request/index.blade.php
@extends('layouts.default')

@section('title', 'Заявки')

@push('css')
    <link href="/assets/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="/assets/plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet" />
@endpush

@section('content')
    <!-- begin breadcrumb -->
    <ol class="breadcrumb float-xl-right">
        <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Рабочий стол</a></li>
        <li class="breadcrumb-item active">Заявки</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Заявки</h1>
    <!-- end page-header -->
    <!-- begin panel -->
    <div class="panel panel-inverse">
        <!-- begin panel-heading -->
        <div class="panel-heading">
            <h4 class="panel-title">Список заявок</h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
            </div>
        </div>
        <!-- end panel-heading -->
        <!-- begin panel-body -->
        <div class="panel-body">

            <table id="data-table-fixed-columns" class="table table-striped table-bordered table-td-valign-middle" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th width="1%">#</th>
                    <th class="text-nowrap">ФИО</th>
                    <th class="text-nowrap">Э-почта</th>
                    <th class="text-nowrap">Контакт</th>
                    <th class="text-nowrap">Тема</th>
                    <th class="text-nowrap">Сообщение</th>
                    <th class="text-nowrap">Дата заявок</th>
                    <th class="text-nowrap">Статус</th>
                    <th class="text-nowrap">Действие</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($requests as $item)
                        <tr>
                            <td>{{ $loop->index + 1 }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->email }}</td>
                            <td>{{ $item->phone }}</td>
                            <td>{{ $item->subject }}</td>
                            <td>{!! mb_substr($item->message, 0,22) !!} ...</td>
                            <td>{{ date('d.m.Y H:i', strtotime($item->created_at)) }}</td>
                            <td>@if($item->status == true) <p style="color: green">Просмотрено</p> @else <p style="color: red">Не видел</p> @endif </td>
                            <td align="center">
                                <a href="{{ route('admin.request.show', ['request' => $item->id]) }}" class="btn btn-icon btn-primary"><i class="fas fa-eye"></i></a>
                            </td>
                        </tr>
                    @endforeach
				</tbody>
			</table>
		</div>
        </div>
        <!-- end panel-body -->
	</div>
	<!-- end panel -->
@endsection

@push('scripts')
	<script src="/assets/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
	<script src="/assets/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
	<script src="/assets/plugins/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
	<script src="/assets/plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
    <script>
        if ($('#data-table-fixed-columns').length !== 0) {
            $('#data-table-fixed-columns').DataTable({
                scrollY:        300,
                scrollX:        true,
                scrollCollapse: true,
                fixedColumns: true,
            });
        }
    </script>
@endpush

resources/views/pages/request/show.blade.php
@extends('layouts.default')

@section('title', 'Заявки')

@section('content')
    <!-- begin breadcrumb -->
    <ol class="breadcrumb float-xl-right">
        <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Рабочий стол</a></li>
        <li class="breadcrumb-item"><a href="{{route('admin.request.index')}}">Заявки</a></li>
        <li class="breadcrumb-item active">Показывать</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Показывать</h1>
    <!-- end page-header -->
    <!-- begin panel -->
    <div class="panel panel-inverse" style="background: #f4f4f7">
        <!-- begin panel-heading -->
        <div class="panel-heading">
            <h4 class="panel-title"></h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
            </div>
        </div>
        <!-- end panel-heading -->
        <form>
            <div class="panel-body p-t-10">
            {{--    <div class="row">
                    <div class="col-2">
                        <label for="fio" class="font-weight-bold">ФИО:</label>
                        <p>{{$request['name']}}</p>
                    </div>
                    <div class="col-2">
                        <label for="fio" class="font-weight-bold">Э-почта:</label>
                        <p>{{$request['email']}}</p>
                    </div>
                    <div class="col-2">
                        <label for="contact" class="font-weight-bold">Контакт:</label>
                        <p>{{$request['phone']}}</p>
                    </div>
                    <div class="col-2">
                        <label for="contact" class="font-weight-bold">Тема:</label>
                        <p>{{$request['subject']}}</p>
                    </div>
                    <div class="col-2">
                        <label for="date" class="font-weight-bold">Дата заявок:</label>
                        <p>{{ date('d.m.Y H:i', strtotime($request->created_at)) }}</p>
                    </div>
                </div>
                <div class="row">
                    <!-- begin col-6 -->
                    <div class="col-12">
                        <label for="message" class="font-weight-bold">Сообщение:</label>
                        <p style="white-space: pre-line;">{!! $request['message'] !!}</p>
                    </div>
                    <!-- end col-6 -->
                </div>--}}
                <div class="row m-3">
                   <table class="table table-bordered m-5">
                       <tbody>
                            <tr>
                                <th>ФИО</th>
                                <td>{{$request['name']}}</td>
                            </tr>
                            <tr>
                                <th>Э-почта</th>
                                <td>{{$request['email']}}</td>
                            </tr>
                            <tr>
                                <th>Контакт</th>
                                <td>{{$request['phone']}}</td>
                            </tr>
                            <tr>
                                <th>Тема</th>
                                <td>{{$request['subject']}}</td>
                            </tr>
                            <tr>
                                <th>Сообщение</th>
                                <td>{{$request['message']}}</td>
                            </tr>
                       </tbody>
                   </table>
                </div>
                <div class="float-right mt-3">
                    <a href="{{route('admin.request.index')}}" class="btn btn-danger">
                        <i class="fas fa-arrow-circle-left"></i> Назад</a>
                </div>
            </div>
        </form>
    </div>
@endsection