routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\Basic\LangController;
use App\Http\Controllers\Admin\Basic\ContactController;
use App\Http\Controllers\Admin\Basic\AboutController;
use App\Http\Controllers\Admin\Request\RequestController;
use App\Http\Controllers\Admin\Dashboard\DashboardController;
use App\Http\Controllers\Admin\User\SettingController;

use App\Http\Controllers\Site\Home\HomeController;
use App\Http\Controllers\Site\About\AboutController as SiteAboutController;
use App\Http\Controllers\Admin\Contact\ContactController as SiteContactController;
use App\Http\Controllers\Site\Team\TeamController as SiteTeamController;
use App\Http\Controllers\Site\Service\ServiceController as SiteServiceController;
use App\Http\Controllers\Site\Blog\BlogController as SiteBlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Site routes
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'siteVisits']
    ], function () {

    Route::name('site.')->group(function() {
        Route::get('/', [HomeController::class, 'index'])->name('index');
        Route::get('/about', [SiteAboutController::class, 'index'])->name('about');
        Route::get('/contacts', [SiteContactController::class, 'index'])->name('contact');
        Route::get('/team', [SiteTeamController::class, 'index'])->name('team');
        Route::get('/services', [SiteServiceController::class, 'index'])->name('service');
        Route::get('/service/details', [SiteServiceController::class, 'details'])->name('service-details');
        Route::get('/blog', [SiteBlogController::class, 'index'])->name('blog');
        Route::get('/blog/details', [SiteBlogController::class, 'details'])->name('blog-details');
        Route::get('/product/{id}', [SiteProductController::class, 'show'])->name('product');
        Route::get('/search', [HomeController::class, 'searchData'])->name('search');
    });
});

// Admin routes
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/admin', function () {
    return redirect('admin/home');
});
Route::prefix('/admin')->name('admin.')->middleware('role:admin')->group(function() {

    Route::get('/home', [DashboardController::class, 'index'])->name('index');

    Route::get('setting/edit',[SettingController::class, 'edit'])->name('setting.edit');
    Route::post('setting/update',[SettingController::class, 'update'])->name('setting.update');

    // Languages
    Route::prefix('languages')->name('language.')->group(function(){
        Route::get('/index', [LangController::class, 'index'])->name('index');
        Route::get('/show/{lang}', [LangController::class, 'show'])->name('show');
        Route::get('/edit/{lang}', [LangController::class, 'edit'])->name('edit');
        Route::get('/create', [LangController::class, 'create'])->name('create');
        Route::post('/store', [LangController::class, 'store'])->name('store');
        Route::post('/update/{lang}', [LangController::class, 'update'])->name('update');
    });

    // Contacts
    Route::prefix('contacts')->name('contact.')->group(function(){
        Route::get('/index', [ContactController::class, 'index'])->name('index');
        Route::get('/edit/{contact}', [SiteContactController::class, 'edit'])->name('edit');
        Route::post('/store', [SiteContactController::class, 'store'])->name('store');
        Route::post('/update/{contact}', [SiteContactController::class, 'update'])->name('update');
    });

    // About
    Route::prefix('about')->name('about.')->group(function(){
        Route::get('/index', [AboutController::class, 'index'])->name('index');
        Route::get('/edit', [AboutController::class, 'edit'])->name('edit');
        Route::post('/update', [AboutController::class, 'update'])->name('update');
    });

    // Requests
    Route::prefix('requests')->name('request.')->group(function(){
        Route::get('/index', [RequestController::class, 'index'])->name('index');
        Route::get('/show/{request}', [RequestController::class, 'show'])->name('show');
    });
});

app/Http/Controllers/Admin/User/SettingController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\UpdateUserRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SettingController extends Controller
{
    public function edit()
    {
        $user = auth()->user();
        return view('pages.setting.edit', compact('user'));
    }

    public function update(UpdateUserRequest $request)
    {
        $data = $request->validated();
        if (!is_null($data['old_password'])) {
            $hashedPassword = Auth::user()->password;
            if (!\Hash::check($data['old_password'], $hashedPassword)) {
                return back()->withErrors(['old_password' => __('auth.password')])->withInput();
            }
        }
        User::edit($data);
        return redirect()->route('admin.setting.edit')->with('message', __('Успешно обновлено'));
    }
}

resources/views/pages/setting/edit.blade.php
@extends('layouts.default')

@section('title', 'Настройки')

@push('css')
    <link href="/assets/plugins/blueimp-gallery/css/blueimp-gallery.min.css" rel="stylesheet"/>
    <link href="/assets/plugins/blueimp-file-upload/css/jquery.fileupload.css" rel="stylesheet"/>
    <link href="/assets/plugins/blueimp-file-upload/css/jquery.fileupload-ui.css" rel="stylesheet"/>
@endpush

@section('content')
	<!-- begin breadcrumb -->
	<ol class="breadcrumb float-xl-right">
		<li class="breadcrumb-item"><a href="{{route('admin.index')}}">Рабочий стол</a> </li>
        <li class="breadcrumb-item active">Редактировать профиль</li>
	</ol>
	<!-- end breadcrumb -->
	<!-- begin page-header -->
	<h1 class="page-header">Редактировать профиль</h1>
	<!-- end page-header -->
	<!-- begin panel -->
	<div class="panel panel-inverse">
		<!-- begin panel-heading -->
		<div class="panel-heading">
			<h4 class="panel-title"></h4>
			<div class="panel-heading-btn">
				<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
			</div>
		</div>
		<!-- end panel-heading -->
		<!-- begin panel-body -->
		<div class="panel-body">
            <form action="{{ route('admin.setting.update') }}" enctype="multipart/form-data" method="POST">
                @csrf
                <div class="row">
                    <div class="col-sm-2">
                        <div class="row">
                            <div class="col-xl-12">
                                <img id="image-src" width="100%" src="{{ asset(auth()->user()->avatar) }}" class="float-right" style="border-radius: 50%">
                            </div>
                            <div class="col-xl-12">
                            <span class="btn btn-primary fileinput-button float-right">
                                <i class="fa fa-fw fa-pencil-alt"></i>
                                <span></span>
                                @error('avatar')
                                    <br>
                                <span class="text-danger">
                                        {{ $message }}
                                    </span>
                                @enderror
                                <input type="file" name="avatar" id="image">
                            </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-10">
{{--                        <div class="row">--}}
                            @if(session()->has('message'))
                                <div class="alert alert-success text-center" role="alert">
                                    {{ session()->get('message') }}
                                </div>
                            @endif
{{--                        </div>--}}

                        <div class="row">
                            <div class="col-xl-6">
                                <label for="name" class="mb-0">Имя</label>
                                @error('name')
                                <br><span class="text-danger">{{ $message }}</span>
                                @enderror
                                <input id="name" type="text" class="form-control mb-3" name="name" value="{{ $user['name'] }}">
                            </div>
                            <div class="col-xl-6">
                                <label for="username" class="mb-0">Имя пользователя</label>
                                @error('username')
                                <br><span class="text-danger">{{ $message }}</span>
                                @enderror
                                <input id="username" type="text" class="form-control mb-3" name="username" value="{{ $user['username'] }}">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <label for="old_password" class="mb-0">Старый пароль</label>
                                @error('old_password')
                                <br><span class="text-danger">{{ $message }}</span>
                                @enderror
                                <input id="old_password" type="password" class="form-control mb-3" name="old_password" value="">
                            </div>
                            <div class="col-xl-6">
                                <label for="password" class="mb-0">Новый пароль</label>
                                @error('password')
                                <br><span class="text-danger">{{ $message }}</span>
                                @enderror
                                <input id="password" type="password" class="form-control mb-3" name="password" value="">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="float-right">
                    <a href="{{route('admin.index')}}" class="btn btn-danger">
                        <i class="fas fa-arrow-circle-left"></i> Назад</a>
                    <button class="btn btn-aqua p-6" type="submit">Сохранить</button>
                </div>
            </form>
        </div>
		<!-- end panel-body -->
	</div>
	<!-- end panel -->
@endsection

@push('scripts')
    <script src="/assets/plugins/blueimp-file-upload/js/jquery.fileupload.js"></script>
    <script src="/assets/plugins/blueimp-file-upload/js/jquery.fileupload-image.js"></script>
    <script>
        document.getElementById('image').onchange = function (evt) {
            let tgt = evt.target || window.event.srcElement,
                files = tgt.files;

            // FileReader support
            if (FileReader && files && files.length) {
                let fr = new FileReader();
                fr.onload = function () {
                    document.getElementById('image-src').src = fr.result;
                }
                fr.readAsDataURL(files[0]);
            }

            // Not supported
            else {
                // fallback -- perhaps submit the input to an iframe and temporarily store
                // them on the server until the user's session ends.
            }
        }
    </script>
@endpush