routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\Basic\LangController;
use App\Http\Controllers\Admin\Basic\ContactController;
use App\Http\Controllers\Admin\Basic\AboutController;
use App\Http\Controllers\Admin\Request\RequestController;
use App\Http\Controllers\Admin\Dashboard\DashboardController;
use App\Http\Controllers\Admin\User\SettingController;

use App\Http\Controllers\Site\Home\HomeController;
use App\Http\Controllers\Site\About\AboutController as SiteAboutController;
use App\Http\Controllers\Admin\Contact\ContactController as SiteContactController;
use App\Http\Controllers\Site\Team\TeamController as SiteTeamController;
use App\Http\Controllers\Site\Service\ServiceController as SiteServiceController;
use App\Http\Controllers\Site\Blog\BlogController as SiteBlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Site routes
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'siteVisits']
    ], function () {

    Route::name('site.')->group(function() {
        Route::get('/', [HomeController::class, 'index'])->name('index');
        Route::get('/about', [SiteAboutController::class, 'index'])->name('about');
        Route::get('/contacts', [SiteContactController::class, 'index'])->name('contact');
        Route::get('/team', [SiteTeamController::class, 'index'])->name('team');
        Route::get('/services', [SiteServiceController::class, 'index'])->name('service');
        Route::get('/service/details', [SiteServiceController::class, 'details'])->name('service-details');
        Route::get('/blog', [SiteBlogController::class, 'index'])->name('blog');
        Route::get('/blog/details', [SiteBlogController::class, 'details'])->name('blog-details');
        Route::get('/product/{id}', [SiteProductController::class, 'show'])->name('product');
        Route::get('/search', [HomeController::class, 'searchData'])->name('search');
    });
});

// Admin routes
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/admin', function () {
    return redirect('admin/home');
});
Route::prefix('/admin')->name('admin.')->middleware('role:admin')->group(function() {

    Route::get('/home', [DashboardController::class, 'index'])->name('index');

    Route::get('setting/edit',[SettingController::class, 'edit'])->name('setting.edit');
    Route::post('setting/update',[SettingController::class, 'update'])->name('setting.update');

    // Languages
    Route::prefix('languages')->name('language.')->group(function(){
        Route::get('/index', [LangController::class, 'index'])->name('index');
        Route::get('/show/{lang}', [LangController::class, 'show'])->name('show');
        Route::get('/edit/{lang}', [LangController::class, 'edit'])->name('edit');
        Route::get('/create', [LangController::class, 'create'])->name('create');
        Route::post('/store', [LangController::class, 'store'])->name('store');
        Route::post('/update/{lang}', [LangController::class, 'update'])->name('update');
    });

    // Contacts
    Route::prefix('contacts')->name('contact.')->group(function(){
        Route::get('/index', [ContactController::class, 'index'])->name('index');
        Route::get('/edit/{contact}', [SiteContactController::class, 'edit'])->name('edit');
        Route::post('/store', [SiteContactController::class, 'store'])->name('store');
        Route::post('/update/{contact}', [SiteContactController::class, 'update'])->name('update');
    });

    // About
    Route::prefix('about')->name('about.')->group(function(){
        Route::get('/index', [AboutController::class, 'index'])->name('index');
        Route::get('/edit', [AboutController::class, 'edit'])->name('edit');
        Route::post('/update', [AboutController::class, 'update'])->name('update');
    });

    // Requests
    Route::prefix('requests')->name('request.')->group(function(){
        Route::get('/index', [RequestController::class, 'index'])->name('index');
        Route::get('/show/{request}', [RequestController::class, 'show'])->name('show');
    });
});

app/Http/Controllers/Site/About/AboutController.php
<?php

namespace App\Http\Controllers\Site\About;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    public function index()
    {
        return view('site.about.about');
    }
}

app/Http/Controllers/Site/Blog/BlogController.php
<?php

namespace App\Http\Controllers\Site\Blog;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    public function index()
    {
        return view('site.blogs.blog');
    }
    public function details()
    {
        return view('site.blogs.blog-details');
    }
}

app/Http/Controllers/Site/Contact/ContactController.php
<?php

namespace App\Http\Controllers\Site\Contact;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    //
}

app/Http/Controllers/Site/Home/HomeController.php
<?php

namespace App\Http\Controllers\Site\Home;

use App\Http\Controllers\Controller;
use App\Models\Banner\Banner;
use App\Models\Basic\About;
use App\Models\Methods\PublicMethod;
use App\Models\Product\Product;
use App\Models\Basic\Lang;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        return view('site.dashboard.index');
    }

    public function searchData(Request $request)
    {
        $response = PublicMethod::searchContent();
        return view('site.search', compact('response'));
    }
}

app/Http/Controllers/Site/Service/ServiceController.php
<?php

namespace App\Http\Controllers\Site\Service;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ServiceController extends Controller
{
    public function index()
    {
        return view('site.services.services');
    }

    public function details()
    {
        return view('site.services.service-details');
    }
}

app/Http/Controllers/Site/Team/TeamController.php
<?php

namespace App\Http\Controllers\Site\Team;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class TeamController extends Controller
{
    public function index()
    {
        return view('site.pages.team');
    }
}

resources/views/site/parts/eventy__item.blade.php
<div class="eventy__item">
    <div class="img">
        <img src="/site/images/eventy.jpg" alt="">
    </div>
    <div class="text">
        <h4>Название мероприятия</h4>
        <h5>Краткая информация</h5>
        <p class="flexis">
            <b>Производитель:</b>
            <span> Kibera Technology LLC</span>
        </p>
        <p class="flexis">
            <b>Телефон:</b>
            <span>+998(93)  777-77-77 </span>
        </p>
        <p class="flexis">
            <b>Период времени: </b>
            <span>01.02.2022 - 01.04.2022</span>
        </p>
        <p class="flexis">
            <b>Адрес:</b>
            <span>Юнусабад район/г.Ташкент /Узбекистан</span>
        </p>
        <a href="#">Скачать</a>
    </div>
</div>

resources/views/site/parts/footer.blade.php
<footer class="footer-area footer-bg">
    <div class="container">
        <div class="footer-top pt-100 pb-70">
            <div class="row">
                <div class="col-lg-4 col-sm-6">
                    <div class="footer-widget">
                        <div class="footer-logo">
                            <a href="index.html">
                                <img src="assets/images/logos/footer-logo.png" alt="Images">
                            </a>
                        </div>
                        <p>
                            Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auct.Aenean, lorem quis bibendum auct. Aenean sollicitudin lorem.
                        </p>
                        <div class="footer-call-content">
                            <h3>Talk to Our Support</h3>
                            <span><a href="tel:+1002-123-4567">+1 002-123-4567</a></span>
                            <i class='bx bx-headphone'></i>
                        </div>
                    </div>
                </div>

                <div class="col-lg-2 col-sm-6">
                    <div class="footer-widget pl-2">
                        <h3>Services</h3>
                        <ul class="footer-list">
                            <li>
                                <a href="service-details.html" target="_blank">
                                    <i class='bx bx-chevron-right'></i>
                                    IT Consultancy
                                </a>
                            </li>
                            <li>
                                <a href="service-details.html" target="_blank">
                                    <i class='bx bx-chevron-right'></i>
                                    Business Solution
                                </a>
                            </li>
                            <li>
                                <a href="service-details.html" target="_blank">
                                    <i class='bx bx-chevron-right'></i>
                                    Digital Services
                                </a>
                            </li>
                            <li>
                                <a href="compare.html" target="_blank">
                                    <i class='bx bx-chevron-right'></i>
                                    Business Reform
                                </a>
                            </li>
                            <li>
                                <a href="service-details.html" target="_blank">
                                    <i class='bx bx-chevron-right'></i>
                                    Web Development
                                </a>
                            </li>
                            <li>
                                <a href="service-details.html" target="_blank">
                                    <i class='bx bx-chevron-right'></i>
                                    Cloud Computing
                                </a>
                            </li>
                            <li>
                                <a href="service-details.html" target="_blank">
                                    <i class='bx bx-chevron-right'></i>
                                    Data Analysis
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-3 col-sm-6">
                    <div class="footer-widget pl-5">
                        <h3>Our Blog</h3>
                        <ul class="footer-blog">
                            <li>
                                <a href="blog-details.html">
                                    <img src="assets/images/blog/blog-img-footer.jpg" alt="Images">
                                </a>
                                <div class="content">
                                    <h3><a href="blog-details.html">Product Idea Solution For New Generation</a></h3>
                                    <span>04 Dec 2020</span>
                                </div>
                            </li>

                            <li>
                                <a href="blog-details.html">
                                    <img src="assets/images/blog/blog-img-footer2.jpg" alt="Images">
                                </a>
                                <div class="content">
                                    <h3><a href="blog-details.html">New Device Invention for Digital Platform</a></h3>
                                    <span>07 Dec 2020</span>
                                </div>
                            </li>

                            <li>
                                <a href="blog-details.html">
                                    <img src="assets/images/blog/blog-img-footer3.jpg" alt="Images">
                                </a>
                                <div class="content">
                                    <h3><a href="blog-details.html">Business Strategy Make His Goal Acheive</a></h3>
                                    <span>10 Dec 2020</span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-3 col-sm-6">
                    <div class="footer-widget">
                        <h3>Newsletter</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum finibus molestie molestie. Phasellus ac rutrum massa, et volutpat nisl. Fusce ultrices suscipit nisl.</p>
                        <div class="newsletter-area">
                            <form class="newsletter-form" data-toggle="validator" method="POST">
                                <input type="email" class="form-control" placeholder="Enter Your Email" name="EMAIL" required autocomplete="off">
                                <button class="subscribe-btn" type="submit">
                                    <i class='bx bx-paper-plane'></i>
                                </button>
                                <div id="validator-newsletter" class="form-result"></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="copy-right-area">
            <div class="copy-right-text">
                <p>
                    Copyright © <script>document.write(new Date().getFullYear())</script> Techex. All Rights Reserved by
                    <a href="https://hibootstrap.com/" target="_blank">HiBootstrap</a>
                </p>
            </div>
        </div>
    </div>
</footer>

resources/views/site/parts/header.blade.php
<!-- Top Header Start -->
<header class="top-header top-header-bg">
    <div class="container-fluid">
        <div class="container-max">
            <div class="row align-items-center">
                <div class="col-lg-7 col-md-6">
                    <div class="top-head-left">
                        <div class="top-contact">
                            <h3>Support By : <a href="tel:+1(212)-255-5511">+1 (212) 255-5511</a></h3>
                        </div>
                    </div>
                </div>

                <div class="col-lg-5 col-md-6">
                    <div class="top-header-right">
                        <div class="top-header-social">
                            <ul>
                                <li>
                                    <a href="https://www.facebook.com/" target="_blank">
                                        <i class='bx bxl-facebook'></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://twitter.com/?lang=en" target="_blank">
                                        <i class='bx bxl-twitter'></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.linkedin.com/" target="_blank">
                                        <i class='bx bxl-linkedin-square'></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.instagram.com/" target="_blank">
                                        <i class='bx bxl-instagram'></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="language-list">
                            <select class="language-list-item">
                                <option>Русскый</option>
                                <option>English</option>
                                <option>O'zbekcha</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Start Navbar Area -->
<div class="navbar-area">
    <!-- Menu For Mobile Device -->
    <div class="mobile-nav">
        <a href="index.html" class="logo">
            <img src="{{asset('assets/images/logos/logo-1.png')}}" class="logo-one" alt="Logo">
            <img src="{{asset('assets/images/logos/logo-2.png')}}" class="logo-two" alt="Logo">
        </a>
    </div>

    <!-- Menu For Desktop Device -->
    <div class="main-nav">
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-light ">
                <a class="navbar-brand" href="index.html">
                    <img src="{{asset('assets/images/logos/logo-1.png')}}" class="logo-one" alt="Logo">
                    <img src="{{asset('assets/images/logos/logo-2.png')}}" class="logo-two" alt="Logo">
                </a>

                <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
                    <ul class="navbar-nav m-auto">
                        <li class="nav-item">
                            <a href="{{route('site.index')}}" class="nav-link">
                                Home

                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('site.about')}}" class="nav-link">
                                About
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                Pages
                                <i class='bx bx-caret-down'></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a href="{{route('site.team')}}" class="nav-link">
                                        Team
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a href="testimonials.html" class="nav-link">
                                        Testimonials
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a href="faq.html" class="nav-link">
                                        FAQ
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        Case study
                                        <i class='bx bx-caret-down'></i>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item">
                                            <a href="case-study.html" class="nav-link">
                                                Case study
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="case-details.html" class="nav-link">
                                                Case study Details
                                            </a>
                                        </li>
                                    </ul>
                                </li>

                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        User
                                        <i class='bx bx-caret-down'></i>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item">
                                            <a href="log-in.html" class="nav-link">
                                                Log In
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="register.html" class="nav-link">
                                                Registration
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="forget-password.html" class="nav-link">
                                                Forget Password
                                            </a>
                                        </li>
                                    </ul>
                                </li>

                                <li class="nav-item">
                                    <a href="terms-condition.html" class="nav-link">
                                        Terms & Conditions
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a href="privacy-policy.html" class="nav-link">
                                        Privacy Policy
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a href="404.html" class="nav-link">
                                        404 page
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a href="coming-soon.html" class="nav-link">
                                        Coming Soon
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                Services
                                <i class='bx bx-caret-down'></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a href="{{route('site.service')}}" class="nav-link">
                                        Services
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{route('site.service-details')}}" class="nav-link">
                                        Service Details
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                Blog
                                <i class='bx bx-caret-down'></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a href="{{route('site.blog')}}" class="nav-link">
                                        Blog
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{route('site.blog-details')}}" class="nav-link">
                                        Blog Details
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a href="{{route('site.contact')}}" class="nav-link">
                                Contact
                            </a>
                        </li>
                    </ul>

                    <div class="nav-side d-display">
                        <div class="nav-side-item">
                            <div class="search-box">
                                <i class='bx bx-search'></i>
                            </div>
                        </div>

                        <div class="nav-side-item">
                            <div class="get-btn">
                                <a href="contact.html" class="default-btn btn-bg-two border-radius-50">Get A Quote <i class='bx bx-chevron-right'></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div class="side-nav-responsive">
        <div class="container-max">
            <div class="dot-menu">
                <div class="circle-inner">
                    <div class="in-circle circle-one"></div>
                    <div class="in-circle circle-two"></div>
                    <div class="in-circle circle-three"></div>
                </div>
            </div>

            <div class="container">
                <div class="side-nav-inner">
                    <div class="side-nav justify-content-center align-items-center">
                        <div class="side-nav-item nav-side">
                            <div class="search-box">
                                <i class='bx bx-search'></i>
                            </div>
                            <div class="get-btn">
                                <a href="contact.html" class="default-btn btn-bg-two border-radius-50">Get A Quote <i class='bx bx-chevron-right'></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Navbar Area -->

<!-- Search Overlay -->
<div class="search-overlay">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="search-layer"></div>
            <div class="search-layer"></div>
            <div class="search-layer"></div>

            <div class="search-close">
                <span class="search-close-line"></span>
                <span class="search-close-line"></span>
            </div>

            <div class="search-form">
                <form>
                    <input type="text" class="input-search" placeholder="Search here...">
                    <button type="submit"><i class='bx bx-search'></i></button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Search Overlay -->

resources/views/site/parts/paginate.blade.php
@if ($paginator->hasPages())

{{--    <nav aria-label="Page navigation example">--}}
        <ul class="pagination">
            {{--            @if ($paginator->onFirstPage())--}}
            {{--                <li class="page-item disabled">--}}
            {{--                    <a class="page-link" href="#" tabindex="-1">Previous</a>--}}
            {{--                </li>--}}
            {{--            @else--}}
            {{--                <li class="page-item"><a class="page-link" href="{{ $paginator->previousPageUrl() }}">Previous</a></li>--}}
            {{--            @endif--}}

            @foreach ($elements as $element)
                @if (is_string($element))
                    <li>{{ $element }}</li>
                @endif

                @if (is_array($element))
                    @foreach ($element as $page => $url)
                        @if ($page == $paginator->currentPage())
                            <li>
                                <a class="active">{{ $page }}</a>
                            </li>
                        @else
                            <li>
                                <a href="{{ $url }}">{{ $page }}</a>
                            </li>
                        @endif
                    @endforeach
                @endif
            @endforeach
        </ul>
@endif