routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\Basic\LangController;
use App\Http\Controllers\Admin\Basic\ContactController;
use App\Http\Controllers\Admin\Basic\AboutController;
use App\Http\Controllers\Admin\Request\RequestController;
use App\Http\Controllers\Admin\Dashboard\DashboardController;
use App\Http\Controllers\Admin\User\SettingController;

use App\Http\Controllers\Site\Home\HomeController;
use App\Http\Controllers\Site\About\AboutController as SiteAboutController;
use App\Http\Controllers\Admin\Contact\ContactController as SiteContactController;
use App\Http\Controllers\Site\Team\TeamController as SiteTeamController;
use App\Http\Controllers\Site\Service\ServiceController as SiteServiceController;
use App\Http\Controllers\Site\Blog\BlogController as SiteBlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Site routes
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'siteVisits']
    ], function () {

    Route::name('site.')->group(function() {
        Route::get('/', [HomeController::class, 'index'])->name('index');
        Route::get('/about', [SiteAboutController::class, 'index'])->name('about');
        Route::get('/contacts', [SiteContactController::class, 'index'])->name('contact');
        Route::get('/team', [SiteTeamController::class, 'index'])->name('team');
        Route::get('/services', [SiteServiceController::class, 'index'])->name('service');
        Route::get('/service/details', [SiteServiceController::class, 'details'])->name('service-details');
        Route::get('/blog', [SiteBlogController::class, 'index'])->name('blog');
        Route::get('/blog/details', [SiteBlogController::class, 'details'])->name('blog-details');
        Route::get('/product/{id}', [SiteProductController::class, 'show'])->name('product');
        Route::get('/search', [HomeController::class, 'searchData'])->name('search');
    });
});

// Admin routes
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/admin', function () {
    return redirect('admin/home');
});
Route::prefix('/admin')->name('admin.')->middleware('role:admin')->group(function() {

    Route::get('/home', [DashboardController::class, 'index'])->name('index');

    Route::get('setting/edit',[SettingController::class, 'edit'])->name('setting.edit');
    Route::post('setting/update',[SettingController::class, 'update'])->name('setting.update');

    // Languages
    Route::prefix('languages')->name('language.')->group(function(){
        Route::get('/index', [LangController::class, 'index'])->name('index');
        Route::get('/show/{lang}', [LangController::class, 'show'])->name('show');
        Route::get('/edit/{lang}', [LangController::class, 'edit'])->name('edit');
        Route::get('/create', [LangController::class, 'create'])->name('create');
        Route::post('/store', [LangController::class, 'store'])->name('store');
        Route::post('/update/{lang}', [LangController::class, 'update'])->name('update');
    });

    // Contacts
    Route::prefix('contacts')->name('contact.')->group(function(){
        Route::get('/index', [ContactController::class, 'index'])->name('index');
        Route::get('/edit/{contact}', [SiteContactController::class, 'edit'])->name('edit');
        Route::post('/store', [SiteContactController::class, 'store'])->name('store');
        Route::post('/update/{contact}', [SiteContactController::class, 'update'])->name('update');
    });

    // About
    Route::prefix('about')->name('about.')->group(function(){
        Route::get('/index', [AboutController::class, 'index'])->name('index');
        Route::get('/edit', [AboutController::class, 'edit'])->name('edit');
        Route::post('/update', [AboutController::class, 'update'])->name('update');
    });

    // Requests
    Route::prefix('requests')->name('request.')->group(function(){
        Route::get('/index', [RequestController::class, 'index'])->name('index');
        Route::get('/show/{request}', [RequestController::class, 'show'])->name('show');
    });
});

app/Models/Basic/Contact.php
<?php

namespace App\Models\Basic;

use App\Models\Methods\PublicMethod;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;

    public static function getData()
    {
        $item = Contact::all()->first();
        if (is_null($item)) {
            $item = [
                "id" => 1,
                "name" => null,
                "email" => null,
                "phone" => null,
                "subject" => null,
                "message" => null,
                "point_x" => null,
                "point_y" => null,
                "created_at" => null,
                "updated_at" => null
            ];
        } else {
            $item = $item->toArray();
        }
        return $item;
    }
}

app/Http/Controllers/Admin/Basic/ContactController.php
<?php

namespace App\Http\Controllers\Admin\Basic;

use App\Http\Controllers\Controller;
use App\Models\Admin\Basic\Map;
use App\Models\Basic\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index()
    {
        $contacts = Contact::all();
       // $map  = Map::all();
        //dd($contacts);
        return view('pages.contact.index',compact('contacts'));
    }
}

app/Http/Controllers/Admin/Contact/ContactController.php
<?php

namespace App\Http\Controllers\Admin\Contact;

use App\Http\Controllers\Controller;
use App\Models\Basic\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index()
    {
        return view('site.contact.contact');
    }
}

app/Http/Controllers/Site/Contact/ContactController.php
<?php

namespace App\Http\Controllers\Site\Contact;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    //
}

resources/views/pages/contact/index.blade.php
@extends('layouts.default')

@section('title', 'Контакты')

@push('css')
	<link href="/assets/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
	<link href="/assets/plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet" />
	<link href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet"/>
    <link href="/assets/plugins/blueimp-gallery/css/blueimp-gallery.min.css" rel="stylesheet"/>
    <link href="/assets/plugins/blueimp-file-upload/css/jquery.fileupload.css" rel="stylesheet"/>
    <link href="/assets/plugins/blueimp-file-upload/css/jquery.fileupload-ui.css" rel="stylesheet"/>
@endpush

@section('content')
	<!-- begin breadcrumb -->
    <ol class="breadcrumb float-xl-right">
        <li class="breadcrumb-item"><a href="#">Рабочий стол</a></li>
        <li class="breadcrumb-item active">Контакты</li>
    </ol>
	<!-- end breadcrumb -->
	<!-- begin page-header -->
	<h1 class="page-header">Контакты</h1>
	<!-- end page-header -->
	<!-- begin panel -->

	<div class="panel panel-inverse">
        <div class="panel-heading">
            <h4 class="panel-title"></h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i
                        class="fa fa-expand"></i></a>
            </div>
        </div>
		<!-- begin panel-body -->
		<div class="panel-body">
			<table id="data-table" class="table table-striped table-bordered table-td-valign-middle ">
				<thead>
					<tr>
						<th width="1%">#</th>
						<th class="text-nowrap">Название</th>
						<th class="text-nowrap">Описани:</th>
						<th class="text-nowrap">Э-почта</th>
						<th class="text-nowrap">Тел.</th>
						<th class="text-nowrap">Действие</th>
					</tr>
				</thead>
				<tbody>
                    @foreach($contacts as $contact)
                        <tr>
                            <td>{{ $loop->index + 1 }}</td>
                            <td>{{ $contact->title }}</td>
                            <td>{{ $contact->description }}</td>
                            <td>{{ $contact->email }}</td>
                            <td>{{ $contact->phone }}</td>
                            <td align="center">
                                <a href="{{route('admin.contact.edit', ['contact' => $contact->id])}}" class="btn btn-icon btn-primary"><i class="fas fa-pencil-alt"></i></a>
                            </td>
                        </tr>
                    @endforeach
				</tbody>
			</table>
            <hr class="m-b-50">
            <div class="row mb-3">
                <div class="col-12">
                    <h6>Расположение на карте</h6>
                    <div id="map" style="height: 300px"></div>
                </div>
            </div>
		</div>
        </div>
        <!-- end panel-body -->
	</div>
	<!-- end panel -->
@endsection

@push('scripts')
	<script src="/assets/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
	<script src="/assets/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
	<script src="/assets/plugins/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
	<script src="/assets/plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
    <script src="/assets/plugins/blueimp-file-upload/js/jquery.fileupload.js"></script>
    <script src="/assets/plugins/blueimp-file-upload/js/jquery.fileupload-image.js"></script>
    <script>
        document.getElementById('image').onchange = function (evt) {
            let tgt = evt.target || window.event.srcElement,
                files = tgt.files;
            // FileReader support
            if (FileReader && files && files.length) {
                let fr = new FileReader();
                fr.onload = function () {
                    document.getElementById('image-src').src = fr.result;
                }
                fr.readAsDataURL(files[0]);
            }
            // Not supported
            else {
            }
        }
    </script>
    <script>
        if ($('#data-table-fixed-columns').length !== 0) {
            $('#data-table-fixed-columns').DataTable({
                scrollY:        300,
                scrollX:        true,
                scrollCollapse: true,
                fixedColumns: true,
            });
        }
    </script>
    <script>
        function changeTypeName(element) {
            let name =  document.getElementById('name')
            if (element.value === 'social') {
               name.value = ''
                $("#name").prop('readonly', false);
            } else {
                name.value = element.options[element.selectedIndex].text
                $("#name").prop('readonly', true);
            }
        }
    </script>

   {{-- <script src="https://api-maps.yandex.ru/2.1/?apikey=72136f46-adf8-474e-a9b7-d5d5d9600b81&lang=ru_RU"
            type="text/javascript"></script>
    <script type="text/javascript">
        ymaps.ready(init);

        function init() {
            let myMap = new ymaps.Map("map", {
                center: [{{$map['point_y']}}, {{$map['point_x']}}],
                zoom: 14,
                draggable: true,
            });
            const collection = new ymaps.GeoObjectCollection(null, {
                preset: 'twirl#redIcon',
                iconContent: ' ',
                hintContent: "",
                balloonContent: "Содержимое <em>балуна</em> метки"
            });
            collection.add(new ymaps.Placemark([{{$map->point_y}}, {{$map->point_x}}], {
                iconContent: ' ',
                hintContent: "",
                balloonContent: "Содержимое <em>балуна</em> метки"
            }));
            myMap.geoObjects.add(collection);
        }
    </script>--}}
@endpush